# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Releases

on:
  workflow_dispatch:
    
jobs:
  build:  
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    steps:
      #----------------------------------------------
      #  Check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      #----------------------------------------------
      #  Configure poetry 
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      #----------------------------------------------
      # Install dependencies 
      #----------------------------------------------
      - name: Install dependencies
        run: poetry install --no-interaction
      #----------------------------------------------
      # Build 
      #----------------------------------------------
      - name: Build
        run: poetry build
    